### ISSUE TITLE
Poetry fails on matrix strategies combinations

### ISSUE THREAD

**Issue by brunolnetto** [snok/install-poetry#113]
Hi,

I try to fix my workflow based on previous developers' experiences with this dependency management system. However, there is still not much still to bring the bugs to fly around. Among others, I cannot setup `matrix.os` as `'windows-latest'` properly. Both, workflow file and error log, are below to consult:

URL: https://github.com/trouchet/appy/actions/runs/3778445115
Error log:
```
To get started you need Poetry's bin directory (C:\Users\runneradmin\.local\bin) in your `PATH`
environment variable.

Alternatively, you can call Poetry explicitly with `C:\Users\runneradmin\.local\bin\poetry`.

You can test that everything is set up by executing:

`poetry --version`

D:\a\_actions\snok\install-poetry\v1/main.sh: line 36: poetry: command not found
```

**Comment by JWCook** [comment]
You're probably running into the same issue as #105. There are more details in the Readme: https://github.com/snok/install-poetry#running-on-windows

**Comment by brunolnetto** [comment]
Great. A last question: it is an issue to me the organization of `install-poetry` to be [Snok](https://www.youtube.com/watch?v=1bU2jzBKdSM) :-/

**Comment by sondrelg** [comment]
Come to the dark side @brunolnetto

**Comment by brunolnetto** [comment]
May I take my googles with me. I am bad-sighted. :-/
