### ISSUE TITLE
Poetry Requires Python 3.8+

### ISSUE THREAD

**Issue by tmakruck** [snok/install-poetry#135]
<img width="244" alt="image" src="https://github.com/snok/install-poetry/assets/122048087/a33f0679-fcdc-4f75-8035-ce5ff6b7a4a9">

Tests in django-auth-adfs are currently failing when python 3.7 is at play. Poetry itself now requires python 3.8+ per https://python-poetry.org/docs/

**Comment by sondrelg** [comment]
Guess it's time to drop support. Python 3.7 has reached EOL right? ([source](https://devguide.python.org/versions/))

**Comment by ulgens** [comment]
This is resolved by https://github.com/snok/install-poetry/pull/136

**Comment by sondrelg** [comment]
Thanks @ulgens
