### ISSUE TITLE
How to change working-directory ?

### ISSUE THREAD

**Issue by Yasu-umi** [snok/install-poetry#139]
Is it possible to add a feature to change the directory where `poetry install` is executed with an optional argument like [working-directory](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory) ?

**Comment by sondrelg** [comment]
If you set the `POETRY_HOME` environment variable, it should be respected I believe. See https://github.com/snok/install-poetry/issues/127 :+1:

**Comment by Yasu-umi** [comment]
Thanks a lot!

**Comment by Yasu-umi** [comment]
@sondrelg Sorry, I misunderstood answer. I'm looking for a way to change the path where 'poetry install' is executed, not where poetry is installed.

**Comment by Yasu-umi** [comment]
I was completely mistaken.. `snok/install-poetry` does not run `poetry install`, so this issue was meaningless.

**Comment by miigotu** [comment]
Just in case this helps or someone else checks this in the future:

```yaml
- name: poetry install
   working-directory: /app
    run: poetry install
```
