### ISSUE TITLE
Calling poetry via CMake script on Windows

### ISSUE THREAD

**Issue by nealkruis** [snok/install-poetry#146]
I have a C++ project where I am using poetry to install packages for some utility scripts we are creating. I am using CMake for the build process where I am calling both:

- [poetry install](https://github.com/bigladder/HPWHsim/blob/fcf5e0131a488022cda50fb434d44ca8e8bbda58/test/CMakeLists.txt#L44), and
- [poetry run python <script>](https://github.com/bigladder/HPWHsim/blob/fcf5e0131a488022cda50fb434d44ca8e8bbda58/test/CMakeLists.txt#L286)

Poetry is correctly added to the path, and everything works as expected on MacOS and Ubuntu. But on Windows, CMake [doesn't seem to be able to find the executable](https://github.com/bigladder/HPWHsim/actions/runs/7505371067/job/20434473864#step:10:1312).

I've confirmed this works on a local Windows machine, so I don't think it's a CMake issue. Is it possible it is an issue with the way this action is setting up the environment on the runner?

I'm wondering if CMake is executing processes outside of the bash shell. It would maybe help if there was some explanation of why the bash shell is needed on Windows.

**Comment by nealkruis** [comment]
@sondrelg any thoughts on this issue?

**Comment by sondrelg** [comment]
I wouldn't expect cmake to make a difference. There was a problem with the windows installation for the recommended installation script earlier, so we had to keep using the old installation script: https://github.com/snok/install-poetry/blob/main/main.sh#L12 - that is probably related. Have you tried installing using `pipx`?

**Comment by nealkruis** [comment]
Installing using `pipx` works! Does the `pipx` installation replace the need for this action?

**Comment by sondrelg** [comment]
Yes, it should in most situations 👍 It's not quite the recommended way, but for ephemeral-runner based workloads it won't make a difference 🙂
