### ISSUE TITLE
Update docs for Windows Server 2019

### ISSUE THREAD

**Issue by MikeWallis42** [snok/install-poetry#148]
I just wanted to share with you something that I've discovered after a few days in the hope that it helps someone else out.

When using the Github runner Windows Server 2019, setup-python needs running before install-poetry otherwise the installation uses the system Python (3.7.9 at time of writing).
If you don't do this then this action returns `Error: Process completed with exit code 127.` when running poetry commands to set configuration because Poetry doesn't seem to get installed properly.

**Comment by sondrelg** [comment]
That makes sense @MikeWallis42, thanks for mentioning it! I *think* all the example in the readme are correct wrt. to this information, so feel like that might be sufficient if true. Going to close this for now on that basis. However, please let me know if you spot anything that's misleading or not right in the readme, and I will be happy to adjust it 👍
