### ISSUE TITLE
poetry installation failed when installing with default settings

### ISSUE THREAD

**Issue by indiVar0508** [snok/install-poetry#149]
Hi

Can you help fix this issue, i want to use gh-action step to install poetry instead of doing pip install but getting this error

```sh
Installing Poetry (1.7.1)
Installing Poetry (1.7.1): Creating environment
Installing Poetry (1.7.1): Installing Poetry
Installing Poetry (1.7.1): An error occurred. Removing partial environment.
Poetry installation failed.
See /home/runner/work/sqlalchemy-history/sqlalchemy-history/poetry-installer-error-fmy718_b.log for error logs.
Error: Process completed with exit code 1.
```

step command that i am using

```sh
- name: Install Poetry
   uses: snok/install-poetry@v1
   with:
      version: "latest"
```

ref job: https://github.com/corridor/sqlalchemy-history/actions/runs/7652428622/job/20852171311
ref workflow file: https://github.com/corridor/sqlalchemy-history/actions/runs/7652428622/workflow

**Comment by Azd325** [comment]
It seems to be the version, with 1.5.1 it runs smoothly for me but I have the same issue with 1.7.1

**Comment by indiVar0508** [comment]
Yes thanks,
it happened because poetry > 1.5.1 does not support py37 and i was installing it against py37 with latest so it failed.
got it resolved closing this thread.
