### ISSUE TITLE
Error in Readme. Default virtualenvs-path is {cache-dir}/virtualenvs

### ISSUE THREAD

**Issue by zalun** [snok/install-poetry#151]
In the `README.md` file the parameters of the `Install Poetry` step do not contain the `virtualenvs-path`.
Later, `Load cache env` step uses the `.venv` directory and fails with a `Cache not found` message.
After adding the `﻿virtualenvs-path: .venv`, everything works as expected.

**Comment by zalun** [comment]
I should read the other issues first...

**Comment by sondrelg** [comment]
Fixed in https://github.com/snok/install-poetry/issues/151 👍 Thanks again 🙂
