### ISSUE TITLE
Error "line 6: python: command not found" after releasing v1.4.0

### ISSUE THREAD

**Issue by oferqm** [snok/install-poetry#158]
Hi,

We use install-poetry action on our local hosted runners as part of our build flow.
After the change to v1.4.0 the action failed with the error `/actions-runner/_work/_actions/snok/install-poetry/v1/main.sh: line 6: python: command not found`

Our runner is running on Ubuntu 22.04.2 LTS 

We work around the problem by forcing the action to work with version v1.3.4

**Comment by djperrefort** [comment]
My organization has the same problem. We have several CI pipelines that are currently broken by this exact error.

**Comment by megaserg** [comment]
Same problem. This was introduced by https://github.com/snok/install-poetry/pull/153.

**Comment by sondrelg** [comment]
I've just released v1.4.1 with @megaserg's fix. Hopefully that should resolve things 👍 Please let me know if not!
