### ISSUE TITLE
 syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by olkuksa** [snok/install-poetry#36]
Run snok/install-poetry@v1.1.6
  with:
    virtualenvs-create: true
    virtualenvs-in-project: true
    version: 1.1.6
    virtualenvs-path: {cache-dir}/virtualenvs
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.10/x64/lib
/tmp/tmp.TEydkfsscF9p: line 2: syntax error near unexpected token `newline'
/tmp/tmp.TEydkfsscF9p: line 2: `<?xml version="1.0" encoding="utf-8"?>'
Error: Process completed with exit code 2.

**Comment by olkuksa** [comment]
Probably https://techcrunch.com/2021/06/08/numerous-popular-websites-are-facing-an-outage/

**Comment by JonasKs** [comment]
Probably yes, CDNs are down. Even GitHub struggles to load CSS atm.

https://downdetector.com/  
https://status.fastly.com/

**Comment by JonasKs** [comment]
Could you try again now? Issues seem to have been resolved.

**Comment by olkuksa** [comment]
Resolved
