### ISSUE TITLE
Add input for POETRY_HOME

### ISSUE THREAD

**Issue by linkous8** [snok/install-poetry#39]
Hi snok

I'm working on a project which caches the poetry installation to speed up our test runs. We recently updated from 1.1.4 to 1.1.6 but the new installation location is not ideal for caching as it would it would be caching the contents of the entire ~/.local directory when we would prefer to cache only the poetry installation

It would be great if the path value used for poetry home could be supplied as an input to the workflow action instead of the currently hard coded implementation here: https://github.com/snok/install-poetry/blob/4315377389fc195a3955c4eacf49b86ca8e73f0f/scripts/v1.2/main.sh#L42

I'll open a pull with a proposed implementation sometime tomorrow

**Comment by sondrelg** [comment]
A PR for this is very welcome 👏   Thanks @linkous8

**Comment by linkous8** [comment]
Unfortunately, implementing this was not as straight forward as I thought it would be, the tests are all blowing up when run in my local repo: https://github.com/linkous8/install-poetry/actions/runs/994929613

Do you have any recommendations where I might be going wrong? If not, I can close out the PR to remove the needless clutter

**Comment by sondrelg** [comment]
Do they pass if you undo the changes? Or do they possibly fail because you're running the tests in a fork? 🙂 

To give you some context: The reason I ended up setting the `POETRY_HOME` variable was because the Github action runners are inconsistent. If I remember correctly mac runners sometimes use `~/.local` and sometime uses `~/Library/Application`.

I can take a better look at it tomorrow if that doesn't help you 👍

**Comment by sondrelg** [comment]
Might be a good idea to comment out most of the tests when experimenting btw 🙂 I usually just keep one or two until I get it to work then comment the rest back in - otherwise it takes forever

**Comment by sondrelg** [comment]
In the final test run it looks like the condition isn't working

```
python3: can't open file 'default': [Errno 2] No such file or directory
```

Looks like it's just setting "default"

**Comment by linkous8** [comment]
Right, I have a conditional to set the path variable but its not working correctly for some reason:

https://github.com/snok/install-poetry/pull/40/files#diff-61368e2b75f4523e4d83149b45fae042b666e423a7d6455784a0a3519351064eR37

**Comment by miigotu** [comment]
@linkous8 why not make the default an empty string?

```yaml
  poetry-home:
    description: "The Poetry installation path"
    required: false
    default: ""
```

```bash
if [ -z "$poetry_home" ]; then
  if [ "$os" == "Windows" ]; then
    path="C:/Users/runneradmin/AppData/Roaming/Python/Scripts/"
  else
    path="$HOME/.local/"
  fi
else
  path="$HOME/.local/"
  path="$poetry_home_path"
fi
```

**Comment by sondrelg** [comment]
That seems sensible 🙂 

Would this make sense @miigotu 

```shell
if [ -z "$poetry_home" ]; then
  if [ "$os" == "Windows" ]; then
    path="C:/Users/runneradmin/AppData/Roaming/Python/Scripts/"
  else
    path="$HOME/.local/"
  fi
else
  path="$poetry_home_path"
fi
```

Or does the second `path="$HOME/.local/"` have a purpose?

**Comment by miigotu** [comment]
Opps that was a typo lol, editing that.

**Comment by linkous8** [comment]
Opted for an alternative approach to caching, I no longer need support for this
