### ISSUE TITLE
`poetry install` stalls on ubuntu-latest

### ISSUE THREAD

**Issue by Sbozzolo** [snok/install-poetry#46]
I don't know if this action is the problem, but I am not exactly sure where else to look, and I've seen other reports of poetry stalling. I've used the action for hundreds of runs, but lately the "Install Dependencies" step has stopped working (example [here](https://github.com/Sbozzolo/kuibit/runs/3185120434) as the installation does not complete (and I have to stop the runner).

This is on ubuntu-latest. Any suggestion on how to debug/fix the problem would be welcome.

**Comment by sondrelg** [comment]
Hi @Sbozzolo! 

Can you try to replace the action with a simple `pip install poetry`, then re-run with the action, and see if they behave differently?

Happy to help debug this 👍  but not sure there's much I can do to help you if it's a Poetry issue rather than an installation issue 🙂

**Comment by Sbozzolo** [comment]
It looks like that the problem is still there ([see here](https://github.com/Sbozzolo/kuibit/runs/3203258642?check_suite_focus=true), so I the problem is somewhere else.

I'll close the issue, but if you have suggestions to find what's wrong, I'd love to hear them!
