### ISSUE TITLE
Question: Can it install poetry from a specific commit?

### ISSUE THREAD

**Issue by mario-bermonti** [snok/install-poetry#59]
There is currently an error with poetry on Windows and the fix has not been integrated into released version. 

The current recommendation is to install using:
`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - --git https://github.com/serverwentdown/poetry.git@1.1-fix-cache-on-windows`

Would something like this be possible with this action?

**Comment by sondrelg** [comment]
Line 46 and 48 here is where we install poetry via the script we curled: https://github.com/snok/install-poetry/blob/main/action.yml#L48

I suppose it would be possible to add a `**kwargs` style solution where users can append any extra commands they desire - that might solve future use-cases while we're at it.

Would you be interested in opening a PR for this?

**Comment by mario-bermonti** [comment]
That sounds good. I’m going to have a go at it and I’ll get back to you. 

I’m a newbie at contributing to other people’s project so bear with me 😂

**Comment by sondrelg** [comment]
If you have any questions, just let us know here 👍 [This](https://github.com/snok/.github/blob/main/CONTRIBUTING.md) document might also help you get started.

**Comment by sondrelg** [comment]
Release v1.3.0 should be ready now @mario-bermonti, if you want to test it 👍

**Comment by mario-bermonti** [comment]
Awesome! I'll test it soon.
