### ISSUE TITLE
.venv/scripts/activate: No such file or directory on Windows

### ISSUE THREAD

**Issue by ethteck** [snok/install-poetry#74]
Hi! thanks for your github action. I unfortunately am having trouble getting it to work on windows...perhaps I'm missing something simple, but I've fiddled with stuff and can't seem to get it.

Failure log:
https://github.com/decompme/decomp.me/runs/5250900347?check_suite_focus=true

Work-in-progress pr.yml with the windows section highlighed: https://github.com/decompme/decomp.me/blob/334938e96d08e43d5687cbd8b94b069b9a45dbe6/.github/workflows/pr.yml#L89

Thanks in advance for your time.

**Comment by sondrelg** [comment]
Looks like it is creating a venv at `D:\a\decomp.me\decomp.me\backend\.venv`. Is `D:\a\decomp.me\decomp.me\backend\` your working directory, and what does `ls D:\a\decomp.me\decomp.me\backend\.venv` output?

**Comment by ethteck** [comment]
Ahhh I see. I thought the venv was not in the working directory. I was able to solve my immediate issue by just installing poetry through pip on Windows...but I'll follow-back up with this if we decide to standardize and use a build matrix. Thanks :)
