### ISSUE TITLE
Support for dependency groups

### ISSUE THREAD

**Issue by Gobot1234** [snok/install-poetry#79]
Is there currently support for https://github.com/python-poetry/poetry/issues/1644 if not could it be added?

**Comment by miigotu** [comment]
This action just installs the poetry tool

**Comment by Gobot1234** [comment]
So `poetry install --with ...` should be ran inside a separate step?

**Comment by miigotu** [comment]
Yes, this action just installs poetry itself. Then you would restore your virtualenv if you cached it and run poetry commands.

**Comment by Gobot1234** [comment]
Ok thank you for the clarification
