### ISSUE TITLE
Use this Github action in Gitlab CI

### ISSUE THREAD

**Issue by dclimber** [snok/install-poetry#83]
Hey, would it be possible to publish this action to Docker Hub?

If the action is published to Docker Hub, then it is possible to use in Gitlab CI.
The details are outlined in this article: https://tomasvotruba.com/blog/how-can-we-use-github-actions-in-gitlab/

If you don't mind, then I can make a PR for it :)

**Comment by sondrelg** [comment]
Is this no longer needed @dclimber ?

**Comment by miigotu** [comment]
If it isn't already done, I might be able to take a crack at it in a few days.

**Comment by sondrelg** [comment]
Closing this for now :slightly_smiling_face: Feel free to reopen if either of you are planning on working on it in the near term
