### ISSUE TITLE
Venv procedure Windows in README

### ISSUE THREAD

**Issue by MrTeferi** [snok/install-poetry#88]
The Venv procedure outlined in the README for using a matrix that includes windows is incorrect.
For windows it would be ".venv/scripts/activate", if you precede that with "source" it will throw an error that there's no command named source. This makes using `source $venv` with a windows workflow impossible unfortunately. Maybe just include "source" in the `$venv` variable and exclude it for windows version?

**Comment by sondrelg** [comment]
I'm pretty sure `source` works if you remember to set the shell as `bash`, no?

**Comment by MrTeferi** [comment]
> 

Could you give me an example workflow for how to do this? I'm still pretty new to workflows, I ended up just eliminating venv from my workflow altogether, but I'm trying to do a workflow that builds an executable for windows, macos, and linux with pyinstaller, you can see my current implementation here (also uses poetry):
https://github.com/MrTeferi/MTG-Art-Downloader/blob/main/.github/workflows/build.yml

**Comment by sondrelg** [comment]
It's described pretty well [here](https://github.com/snok/install-poetry#running-on-windows) I think. You just need to add the `defaults` entry in your workflow file around like 10-11 I think

**Comment by MrTeferi** [comment]
> 

Oh yeah I see the line! I'll give that a shot, thanks!

**Comment by sondrelg** [comment]
Did you manage to get this working @MrTeferi?

**Comment by miigotu** [comment]
I test on windows and calling activate manually is unnecessary. After poetry is run, the env is automatically activated in the workflow

**Comment by sondrelg** [comment]
In that case, I guess we can consider this closed. Thanks @miigotu 👍
